### ISSUE TITLE
Weird bottom padding in paragraphs

### ISSUE THREAD

**Issue by tairosonloa** [JmsPae/jmspae-web#1]
Hello mate! I came across your sit to read your kebab quality study based on the distance to the train station 😂 

It seems there is a really weird bottom padding added to each paragraph. See:

<img width="413" alt="Image" src="https://github.com/user-attachments/assets/4c14454c-35c9-46ce-8ff7-fdbc5007d46d" />

Inspecting your site, I saw the following styles:

```css
section, p {
    padding-right: 12pt;
    padding-left: 12pt;
    padding-bottom: 50%; /* This one is the problem */
}
```

However, it seems like you already removed that from your code (I didn't find it in your sass styles), which makes me wonder that maybe you deployed an old version of your site 🤔 

Anyway, the site is very difficult to read in its actual state. Just letting you know in case you want to fix it 😂
